### ISSUE TITLE
Cant bind global shortcut

### ISSUE THREAD

**Issue by faergeek** [Scumfunk/yamusic#14]
<img width="543" alt="изображение" src="https://user-images.githubusercontent.com/3524621/69222107-d4647580-0b89-11ea-8977-c07f04921b1d.png">

Right now I see the error above. If I click "It doesn't matter", it will work with touchbar. Is it related to #5 also?

P.S. I suppose the error is about physical multimedia keys which are absent when you have touchbar? Sorry, I didn't look at the code yet.

**Comment by marnautov** [comment]
System Preferences -> Security & Privacy -> Accesibility.
Allow Yamusic control your computer and restart application.

**Comment by spinenkoia** [comment]
Hi
I have the same problem, System Preferences -> Security & Privacy -> Accesibility made. The shortcut works
